version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ods1234
      MYSQL_DATABASE: micro-ods
    volumes:
      - ./src/initdb:/docker-entrypoint-initdb.d/
    ports:
      - '3307:3306'

  app:
    build: .
    ports:
      - '3000:3306'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=ods1234
      - DB_NAME=micro-ods
